'use client';
import {useEffect,useRef,useState} from 'react';
import {Play,RotateCcw} from 'lucide-react';
export default function SPHLab(){const c=useRef<HTMLCanvasElement>(null),state=useRef<any>(null),[running,setRunning]=useState(false),[tick,setTick]=useState(0);
useEffect(()=>{const p:any[]=[];for(let y=0;y<17;y++)for(let x=0;x<12;x++)p.push({x:.13+x*.052,y:.12+y*.052,vx:0,vy:0,rho:1000,pressure:0,ax:0,ay:0});state.current={p,t:0};draw();function draw(){const canvas=c.current;if(!canvas)return;const ctx=canvas.getContext('2d')!;ctx.clearRect(0,0,760,250);ctx.fillStyle='#122f31';ctx.fillRect(0,0,760,250);ctx.strokeStyle='#345150';for(let x=0;x<760;x+=38){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,250);ctx.stroke();}ctx.strokeStyle='#addcc9';ctx.strokeRect(16,12,725,221);ctx.fillStyle='#50e0d4';for(const a of p){ctx.beginPath();ctx.arc(18+a.x/3.4*720,232-a.y/1.1*218,3.1,0,Math.PI*2);ctx.fill();}}},[tick]);
useEffect(()=>{if(!running)return;let raf:number;const h=.11,h2=h*h,m=1000*.052**2,dt=.0008,kpoly=4/(Math.PI*h**8),kgrad=-30/(Math.PI*h**5),visc=40/(Math.PI*h**5);
const step=()=>{const s=state.current;if(!s)return;for(let sub=0;sub<28;sub++){const buckets=new Map<string,number[]>();s.p.forEach((a:any,i:number)=>{const key=`${Math.floor(a.x/h)},${Math.floor(a.y/h)}`;if(!buckets.has(key))buckets.set(key,[]);buckets.get(key)!.push(i);});const neighbors=(a:any)=>{const list:number[]=[];const ix=Math.floor(a.x/h),iy=Math.floor(a.y/h);for(let dx=-1;dx<=1;dx++)for(let dy=-1;dy<=1;dy++)list.push(...(buckets.get(`${ix+dx},${iy+dy}`)??[]));return list;};for(const a of s.p){a.near=neighbors(a);a.rho=0;for(const j of a.near){const b=s.p[j],r2=(a.x-b.x)**2+(a.y-b.y)**2;if(r2<h2)a.rho+=m*kpoly*(h2-r2)**3;}a.pressure=Math.max(0,400*(a.rho-1000));}
for(const a of s.p){a.ax=0;a.ay=-9.81;for(const j of a.near){const b=s.p[j],rx=a.x-b.x,ry=a.y-b.y,r=Math.sqrt(rx*rx+ry*ry);if(r>1e-7&&r<h){const f=-m*(a.pressure/(a.rho*a.rho)+b.pressure/(b.rho*b.rho))*kgrad*(h-r)**2/r;const v=.08*m/b.rho*visc*(h-r);a.ax+=f*rx+v*(b.vx-a.vx);a.ay+=f*ry+v*(b.vy-a.vy);}}}
for(const a of s.p){a.vx+=a.ax*dt;a.vy+=a.ay*dt;a.x+=a.vx*dt;a.y+=a.vy*dt;if(a.x<.02){a.x=.02;a.vx=Math.abs(a.vx)*.25;}if(a.x>3.38){a.x=3.38;a.vx=-Math.abs(a.vx)*.25;}if(a.y<.025){a.y=.025;a.vy=Math.abs(a.vy)*.2;}if(a.y>1.08){a.y=1.08;a.vy=-Math.abs(a.vy)*.2;}}s.t+=dt;}
const ctx=c.current?.getContext('2d');if(ctx){ctx.fillStyle='#122f31';ctx.fillRect(0,0,760,250);ctx.strokeStyle='#345150';for(let x=0;x<760;x+=38){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,250);ctx.stroke();}ctx.strokeStyle='#addcc9';ctx.strokeRect(16,12,725,221);for(const a of s.p){ctx.fillStyle=a.rho>1100?'#2e9bfa':'#50e0d4';ctx.beginPath();ctx.arc(18+a.x/3.4*720,232-a.y/1.1*218,3.1,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#daeeea';ctx.font='14px monospace';ctx.fillText(`t = ${s.t.toFixed(2)} s`,630,30);}if(s.t<5)raf=requestAnimationFrame(step);else setRunning(false);};raf=requestAnimationFrame(step);return()=>cancelAnimationFrame(raf);},[running]);
return <section className="panel sph-panel"><div className="panel-heading"><div><h3>SPH dam-break laboratory<span className="s-badge amber" style={{marginLeft:8}}>EDUCATIONAL EXPLAINER</span></h3><p>204 fluid particles · 2D tank experiment</p></div><div className="button-row"><button className="btn secondary" onClick={()=>{setRunning(false);setTick(t=>t+1);}}><RotateCcw size={15}/>Reset</button><button className="btn primary" onClick={()=>setRunning(r=>!r)}><Play size={15}/>{running?'Pause':'Release water'}</button></div></div><canvas ref={c} width="760" height="250" className="sph-canvas"/><p className="footnote">A working weakly compressible SPH demonstration with pressure, viscosity and gravity. Simplified wall collisions; not DualSPHysics, a calibrated benchmark, or a geospatial flood forecast.</p></section>;
}
