'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus,Minus,LocateFixed,Layers,Navigation,MapPin} from 'lucide-react';
import {Grid,Result} from '@/lib/model';
import {Switch} from '@/components/ui/switch';
export function TerrainMap({grid,result,frame,layer,valueKind="depth",wetMask,assets,observed,onSource,sourceIndex,picking=false}:{grid:Grid;result:Result|null;frame:number;layer:string;valueKind?:string;wetMask?:number[];assets:any[];observed?:any;onSource?:(i:number)=>void;sourceIndex?:number;picking?:boolean}){
 const ref=useRef<HTMLCanvasElement>(null);const [zoom,setZoom]=useState(grid.hillshade?2:1),[pan,setPan]=useState(grid.hillshade?{x:.48,y:.1}:{x:0,y:0}),[hover,setHover]=useState<any>(null),[showAssets,setShowAssets]=useState(true),[showWater,setShowWater]=useState(true),[controls,setControls]=useState(false);const drag=useRef<any>(null);
 const depth=result?(layer==='max'?result.maxDepth:result.frames[Math.min(frame,result.frames.length-1)]?.depth):null;
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;canvas.width=grid.nx;canvas.height=grid.ny;const im=ctx.createImageData(grid.nx,grid.ny);if(depth&&showWater)for(let i=0;i<depth.length;i++){const d=depth[i];if(wetMask?wetMask[i]<.3:valueKind==='arrival'?d<0:d<.3)continue;const bands=valueKind==='velocity'?[5,2,1,.5]:valueKind==='arrival'?[60,30,15,5]:[20,10,3,1];const c=d>bands[0]?[68,86,238]:d>bands[1]?[31,140,239]:d>bands[2]?[29,198,229]:d>bands[3]?[67,222,212]:[157,245,223];im.data.set([...c,225],i*4);}ctx.putImageData(im,0,0);},[depth,grid,showWater,wetMask,valueKind]);
 const percent=(lon:number,lat:number)=>({x:(lon-grid.west)/(grid.east-grid.west)*100,y:(grid.north-lat)/(grid.north-grid.south)*100});
 const getPoint=(e:any)=>{const b=e.currentTarget.getBoundingClientRect();const x=((e.clientX-b.left)/b.width-.5-pan.x)*100/zoom+50,y=((e.clientY-b.top)/b.height-.5-pan.y)*100/zoom+50;const ix=Math.floor(x/100*grid.nx),iy=Math.floor(y/100*grid.ny);return {x,y,i:iy*grid.nx+ix,valid:ix>=0&&iy>=0&&ix<grid.nx&&iy<grid.ny};};
 const source=sourceIndex??result?.params.sourceIndex??grid.sourceIndex;const sp={x:(source%grid.nx+.5)/grid.nx*100,y:(Math.floor(source/grid.nx)+.5)/grid.ny*100};
 return <div className={'terrain-map '+(picking?'picking':'')} onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};}} onPointerMove={e=>{if(drag.current&&e.buttons===1&&!picking){const b=e.currentTarget.getBoundingClientRect();setPan({x:drag.current.px+(e.clientX-drag.current.x)/b.width,y:drag.current.py+(e.clientY-drag.current.y)/b.height});}const pt=getPoint(e);setHover(pt.valid?{...pt,depth:depth?.[pt.i]??0,z:grid.z[pt.i]}:null);}} onPointerUp={e=>{if(picking){const p=getPoint(e);if(p.valid)onSource?.(p.i);}drag.current=null;}} onPointerLeave={()=>{setHover(null);drag.current=null;}}>
  <div className="map-world" style={{transform:`translate(${pan.x*100}%,${pan.y*100}%) scale(${zoom})`}}>
   {grid.hillshade?<img src={grid.hillshade} className="relief" alt={'Hillshaded elevation data of '+grid.name} draggable={false}/>:<ElevationCanvas grid={grid}/>}
   <div className="map-grid"/><canvas ref={ref} className="flood-canvas" aria-label="Computed flood depth raster"/>
   {observed&&<svg viewBox="0 0 100 100" preserveAspectRatio="none" className="observed-polygons">{observed.features.slice(0,20000).map((f:any,i:number)=><polygon key={i} points={f.geometry.coordinates[0].map((p:number[])=>{const a=percent(p[0],p[1]);return `${a.x},${a.y}`;}).join(' ')} fill="#fcbb55" fillOpacity=".4" stroke="#fcbb55" strokeWidth=".08"/>)}</svg>}
   <div className="dam-pin" style={{left:sp.x+'%',top:sp.y+'%'}}><span><WavesMini/></span><b>INFLOW LOCATION</b><em>Selected source</em></div>
   {showAssets&&assets.map((a,i)=>{const p=percent(a.lon,a.lat);return <span key={i} className="asset-dot" style={{left:p.x+'%',top:p.y+'%'}} title={a.name}/>;})}
  </div>
  <div className="map-topline"><span className="map-chip"><span className="tiny-dot"/>{valueKind==='velocity'?'Maximum cell velocity':valueKind==='arrival'?'First wetting time':layer==='max'?'Maximum inundation':'Flood progression'}</span><span className="map-chip muted">{Math.round(grid.dx)} m grid · EPSG:4326</span></div>
  <div className="map-tools" onPointerDown={e=>e.stopPropagation()}><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(4,z+.3))}><Plus size={17}/></button><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(1,z-.3))}><Minus size={17}/></button><i/><button aria-label="Reset map view" onClick={()=>{setZoom(1);setPan({x:0,y:0});}}><LocateFixed size={17}/></button><button aria-label="Map layers" onClick={()=>setControls(!controls)}><Layers size={17}/></button></div>
  {controls&&<div className="map-layer-menu" onPointerDown={e=>e.stopPropagation()}><label>Flood depth<Switch checked={showWater} onCheckedChange={setShowWater}/></label><label>Exposure points<Switch checked={showAssets} onCheckedChange={setShowAssets}/></label></div>}
  <div className="north"><Navigation size={23}/><b>N</b></div>
  {picking&&<div className="pick-message"><MapPin size={15}/> Click a terrain cell to set the inflow source</div>}
  <div className="depth-legend"><b>{valueKind==='velocity'?'VELOCITY':valueKind==='arrival'?'ARRIVAL TIME':'WATER DEPTH'} <span>{valueKind==='velocity'?'m/s':valueKind==='arrival'?'min':'m'}</span></b><div className="color-ramp"/><div>{(valueKind==='velocity'?['0','.5','1','2','5+']:valueKind==='arrival'?['0','5','15','30','60+']:['0.3','1','3','10','20+']).map(v=><span key={v}>{v}</span>)}</div></div>
  <div className="map-bottom"><span>Terrain: {grid.source}</span><span>{hover?`${hover.z.toFixed(0)} m elevation · ${(valueKind==='arrival'&&hover.depth<0?'Not reached':hover.depth.toFixed(2))} ${valueKind==='velocity'?'m/s velocity':valueKind==='arrival'?'min arrival':'m depth'}`:'Drag to pan · Hover to inspect'}</span></div>
 </div>;
}
function WavesMini(){return <svg width="18" height="18" viewBox="0 0 20 20"><path d="M2 6q4-5 8 0t8 0M2 12q4-5 8 0t8 0" fill="none" stroke="currentColor" strokeWidth="2"/></svg>}
function ElevationCanvas({grid}:{grid:Grid}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current;if(!c)return;c.width=grid.nx;c.height=grid.ny;const ctx=c.getContext('2d')!;const im=ctx.createImageData(grid.nx,grid.ny),min=Math.min(...grid.z),range=Math.max(...grid.z)-min||1;grid.z.forEach((v,i)=>{const t=(v-min)/range;im.data.set([25+t*60,42+t*70,39+t*67,255],i*4);});ctx.putImageData(im,0,0);},[grid]);return <canvas className="relief" ref={ref}/>;}
