export type Grid = {name:string;source:string;nx:number;ny:number;west:number;east:number;north:number;south:number;dx:number;dy:number;z:number[];sourceIndex:number;hillshade?:string};
export type Params={head:number;width:number;formation:number;duration:number;roughness:number;mode:string;release:number;volume:number;sourceIndex:number;gates?:number;ramp?:number;hydrograph?:{time:number;flow:number}[]};
export type Frame={time:number;velocity?:number[];depth:number[];area:number;maxDepth:number;volume:number;inflow:number};
export type Result={maxVelocity?:number[];engine?:string;createdAt?:string;name?:string;severity?:number;interpolated?:boolean;frames:Frame[];maxDepth:number[];arrival:number[];hydrograph:{time:number;flow:number}[];massError:number;inflowVolume:number;outflowVolume:number;params:Params;grid:Grid;runtime:number;peakFlow?:number};
export const defaults:Params={head:40,width:120,formation:15,duration:60,roughness:0.045,mode:'breach',release:1800,volume:100,sourceIndex:0};
export function download(name:string,body:string|Blob,type='application/json'){const url=URL.createObjectURL(body instanceof Blob?body:new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.style.display="none";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
export function featureCollection(r:Result,depth=r.maxDepth){const g=r.grid; const features=[];for(let y=0;y<g.ny;y++)for(let x=0;x<g.nx;x++){const i=y*g.nx+x;if(depth[i]<0.3)continue;const w=g.west+x*(g.east-g.west)/g.nx,e=w+(g.east-g.west)/g.nx,n=g.north-y*(g.north-g.south)/g.ny,s=n-(g.north-g.south)/g.ny;features.push({type:'Feature',properties:{depth_m:+depth[i].toFixed(3),arrival_min:r.arrival[i]<0?null:+r.arrival[i].toFixed(2),model:'local-inertial prototype',source:g.source},geometry:{type:'Polygon',coordinates:[[[w,n],[e,n],[e,s],[w,s],[w,n]]]}});}return {type:'FeatureCollection',features};}
export function exportKML(r:Result){const fc=featureCollection(r);const placemarks=fc.features.map((f,i)=>`<Placemark><name>Flood cell ${i+1}</name><ExtendedData><Data name="depth_m"><value>${f.properties.depth_m}</value></Data><Data name="arrival_min"><value>${f.properties.arrival_min??''}</value></Data></ExtendedData><styleUrl>#flood</styleUrl><Polygon><outerBoundaryIs><LinearRing><coordinates>${f.geometry.coordinates[0].map(p=>p.join(',')+',0').join(' ')}</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark>`).join('');return `<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>Sentriq — screening scenario, not an operational forecast</name><Style id="flood"><PolyStyle><color>aaefba2b</color></PolyStyle><LineStyle><width>0</width></LineStyle></Style>${placemarks}</Document></kml>`;}
export function parseASC(text:string,name:string):Grid{const lines=text.trim().split(/\r?\n/);const h:Record<string,number>={};let start=0;for(;start<lines.length;start++){const a=lines[start].trim().split(/\s+/);if(!/^[a-zA-Z_]+$/.test(a[0]))break;h[a[0].toLowerCase()]=Number(a[1]);}const nx=h.ncols,ny=h.nrows,c=h.cellsize;if(!Number.isInteger(nx)||!Number.isInteger(ny)||nx<3||ny<3||nx*ny>60000||!Number.isFinite(c)||c<=0)throw Error('Use an ASCII grid with 3–60,000 cells and positive cellsize.');const west=h.xllcorner??h.xllcenter-c/2,south=h.yllcorner??h.yllcenter-c/2;if(!Number.isFinite(west)||!Number.isFinite(south)||west< -180||west+nx*c>180||south< -85||south+ny*c>85||c>0.1)throw Error('Only WGS84 longitude/latitude grids are supported. Reproject to EPSG:4326.');const z=lines.slice(start).join(' ').trim().split(/\s+/).map(Number);if(z.length!==nx*ny||z.some(v=>!Number.isFinite(v)||v===h.nodata_value))throw Error('Grid must have exactly ncols × nrows valid elevations; fill NoData cells before import.');const north=south+ny*c;return {name,source:'User-uploaded DEM · WGS84',nx,ny,west,east:west+nx*c,south,north,dx:c*111320*Math.cos((south+north)/2*Math.PI/180),dy:c*111320,z,sourceIndex:Math.floor(ny/2)*nx+Math.floor(nx/2)};}
export function pointIndex(g:Grid,lon:number,lat:number){const x=Math.floor((lon-g.west)/(g.east-g.west)*g.nx),y=Math.floor((g.north-lat)/(g.north-g.south)*g.ny);return x<0||y<0||x>=g.nx||y>=g.ny?-1:y*g.nx+x;}
export function parseResult(text:string,g:Grid){const fc=JSON.parse(text);if(fc.type!=='FeatureCollection'||!Array.isArray(fc.features)||!fc.features.length||fc.features.length>100000)throw Error('Supply a nonempty GeoJSON FeatureCollection, up to 100,000 features.');let sum=0,max=0,valid=0;for(const f of fc.features){const d=f.properties?.depth_m;if(typeof d!=='number'||!Number.isFinite(d)||d<0)throw Error('Each feature needs a numeric, nonnegative depth_m property.');if(f.geometry?.type!=='Polygon'||f.geometry.coordinates.length!==1)throw Error('Use simple Polygon cells without holes in WGS84.');const ring=f.geometry.coordinates[0];if(ring.length<4||ring[0][0]!==ring[ring.length-1][0]||ring[0][1]!==ring[ring.length-1][1]||ring.some((p:number[])=>p.length<2||!p.every(Number.isFinite)||p[0]<g.west||p[0]>g.east||p[1]<g.south||p[1]>g.north))throw Error('All polygons must fall inside the active DEM bounds.');let a=0;for(let i=0;i<ring.length-1;i++)a+=ring[i][0]*ring[i+1][1]-ring[i+1][0]*ring[i][1];if(d>=0.3)sum+=Math.abs(a)/2*111320**2*Math.cos((g.north+g.south)/2*Math.PI/180)/1e6;max=Math.max(max,d);valid++;}return {fc,area:sum,max,count:valid};}
