'use client';
import {useEffect,useRef} from 'react';
import type {Grid,Result} from '@/lib/model';
export default function TerrainCanvas({grid,result,frame,reset}:{grid:Grid;result:Result|null;frame:number;reset:number}){
 const ref=useRef<HTMLCanvasElement>(null),rotation=useRef(-.53),zoom=useRef(1),drag=useRef<{x:number;yaw:number}|null>(null),paint=useRef(()=>{});
 useEffect(()=>{rotation.current=-.53;zoom.current=1;paint.current();},[reset]);
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;const g=grid,sx=g.sourceIndex%g.nx,sy=Math.floor(g.sourceIndex/g.nx),x0=Math.max(0,sx-25),x1=Math.min(g.nx-1,sx+35),y0=Math.max(0,sy-19),y1=Math.min(g.ny-1,sy+55),min=Math.min(...g.z),max=Math.max(...g.z),range=Math.max(1,max-min),depth=result?.frames[frame]?.depth??result?.maxDepth;
 const draw=()=>{const box=canvas.getBoundingClientRect(),w=box.width,h=box.height,dpr=Math.min(devicePixelRatio,1.6);if(!w||!h)return;canvas.width=w*dpr;canvas.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const scale=Math.min(w/18.2,h/12)*zoom.current,cx=w*.52,cy=h*.64,c=Math.cos(rotation.current),s=Math.sin(rotation.current);const project=(x:number,y:number,z:number)=>{const a=(x-x0)/(x1-x0)*12-6,b=(y-y0)/(y1-y0)*10-5,rx=a*c-b*s,rz=a*s+b*c;return {x:cx+rx*scale,y:cy+rz*scale*.46-(z-min)/range*scale*3.1,rz};};const path=(ps:{x:number;y:number}[])=>{ctx.beginPath();ps.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();};
 ctx.strokeStyle='#25525e33';ctx.lineWidth=.65;for(let k=-4;k<=16;k++){const a=project(x0+(x1-x0)*k/12,y0-(y1-y0)*.25,min-80),b=project(x0+(x1-x0)*k/12,y1+(y1-y0)*.25,min-80);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();const d=project(x0-(x1-x0)*.25,y0+(y1-y0)*k/12,min-80),e=project(x1+(x1-x0)*.25,y0+(y1-y0)*k/12,min-80);ctx.beginPath();ctx.moveTo(d.x,d.y);ctx.lineTo(e.x,e.y);ctx.stroke();}
 const polys:{p:{x:number;y:number;rz:number}[];fill:string;line?:string;rz:number}[]=[];const add=(coords:number[][],fill:string,line?:string)=>{const p=coords.map(a=>project(a[0],a[1],a[2]));polys.push({p,fill,line,rz:p.reduce((a,b)=>a+b.rz,0)/p.length});};
 for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){const i=y*g.nx+x,z=g.z[i],zR=g.z[i+1],zD=g.z[i+g.nx],zRD=g.z[i+g.nx+1],t=(z-min)/range,slope=Math.max(-.32,Math.min(.38,(z-zR+zD-z)/700)),a=Math.max(0,Math.min(1,t+slope));const fill=`rgb(${Math.round(27+a*49)},${Math.round(62+a*63)},${Math.round(72+a*64)})`;add([[x,y,z],[x,y+1,zD],[x+1,y+1,zRD],[x+1,y,zR]],fill,z%130<14?'#8bceca23':'#21475435');if(depth&&depth[i]>=.3){const d=depth[i],level=z+d+8;add([[x,y,level],[x,y+1,level],[x+1,y+1,level],[x+1,y,level]],d>20?'#39a7dfe8':d>3?'#50dce4ee':'#8cedd6e8','#91ffe066');}}
 for(let x=x0;x<x1;x++){for(const y of [y0,y1])add([[x,y,g.z[y*g.nx+x]],[x+1,y,g.z[y*g.nx+x+1]],[x+1,y,min-80],[x,y,min-80]],'#183b4a','#2d596855');}for(let y=y0;y<y1;y++){for(const x of [x0,x1])add([[x,y,g.z[y*g.nx+x]],[x,y+1,g.z[(y+1)*g.nx+x]],[x,y+1,min-80],[x,y,min-80]],'#153442','#2b526055');}
 polys.sort((a,b)=>a.rz-b.rz);for(const poly of polys){path(poly.p);ctx.fillStyle=poly.fill;ctx.fill();if(poly.line){ctx.strokeStyle=poly.line;ctx.lineWidth=.35;ctx.stroke();}}
 const p=project(sx,sy,g.z[g.sourceIndex]);ctx.strokeStyle='#aaf3dd';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x,p.y-35);ctx.stroke();ctx.fillStyle='#bdffe8';ctx.beginPath();ctx.arc(p.x,p.y-36,2.4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e0b680';ctx.fillRect(p.x-6,p.y-2,12,3);ctx.font='7px Arial';ctx.fillStyle='#add6d7';ctx.fillText('INFLOW',p.x+7,p.y-32);
 };paint.current=draw;draw();const ro=new ResizeObserver(draw);ro.observe(canvas);return()=>ro.disconnect();},[grid,result,frame]);
 return <canvas ref={ref} className="software-terrain" aria-label="Interactive projected elevation mesh rendered from the DEM" onPointerDown={e=>{drag.current={x:e.clientX,yaw:rotation.current};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(drag.current){rotation.current=drag.current.yaw+(e.clientX-drag.current.x)*.006;paint.current();}}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null} onWheel={e=>{zoom.current=Math.max(.6,Math.min(1.5,zoom.current-e.deltaY*.0007));paint.current();}}/>;
}
