'use client';
import {useEffect,useState} from 'react';
import {Slider} from '@/components/ui/slider';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Check,ArrowUpRight} from 'lucide-react';
export function SelectField({value,onChange,options,label,ariaLabel}:any){return <label className="s-field">{label&&<span>{label}</span>}<Select value={value} onValueChange={onChange}><SelectTrigger aria-label={ariaLabel??label??'Select option'} className="s-select"><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l]:string[])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></label>}
export function Num({label,value,onChange,min=0,max=10000,step=1,unit}:any){const [draft,setDraft]=useState(String(value));useEffect(()=>setDraft(String(value)),[value]);return <label className="s-field"><span>{label}</span><div className="num-input"><input type="number" aria-label={label} min={min} max={max} step={step} value={draft} onChange={e=>{setDraft(e.target.value);const v=Number(e.target.value);if(e.target.value!==''&&Number.isFinite(v)&&v>=min&&v<=max)onChange(v);}} onBlur={()=>{const v=Number(draft),next=draft!==''&&Number.isFinite(v)?Math.min(max,Math.max(min,v)):value;setDraft(String(next));onChange(next);}}/><small>{unit}</small></div></label>}
export function Range({label,value,onChange,min=25,max=100,step=1,unit='%',disabled=false}:any){return <div className="s-range"><div><span>{label}</span><strong>{value}<small>{unit}</small></strong></div><Slider aria-label={label} value={[value]} min={min} max={max} step={step} disabled={disabled} onValueChange={a=>onChange(a[0])}/><div className="range-labels"><span>{min}{unit}</span><span>{max}{unit}</span></div></div>}
export function Badge({children,tone='neutral'}:any){return <span className={'s-badge '+tone}>{tone==='ready'&&<Check size={11}/>} {children}</span>}
export function Empty({title,children,icon:Icon}:any){return <div className="s-empty">{Icon&&<Icon size={29}/>}<h3>{title}</h3><p>{children}</p></div>}
export function SourceLink({href,children}:any){return <a className="source-link" href={href} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={15}/></a>}
